name: Ubuntu image build
on:
  workflow_dispatch:
    inputs:
      series:
        description: Ubuntu series to build
        required: true
        default: focal
        type: string
      bootstrap_mirror:
        description: Mirror to use to bootstrap the system
        required: true
        default: http://archive.ubuntu.com/ubuntu
        type: string

jobs:
  debootstrap:
    runs-on: ubuntu-latest
    steps:
      - name: installing debootstrap
        run: sudo apt-get install -qqy debootstrap
      - name: creating rootfs directory
        run: mkdir ./rootfs
      - name: running debootstrap
        run: sudo debootstrap ${{ github.event.inputs.series }} ./rootfs ${{ github.event.inputs.bootstrap_mirror }}
      - name: creating tarball
        run: sudo tar czvf rootfs.tar.gz ./rootfs
      - name: Saving rootfs tarball
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.inputs.series }}-rootfs
          path: rootfs.tar.gz
