name: Ubuntu image build
on:
  workflow_dispatch:
    inputs:
      series:
        description: Ubuntu series to build
        required: true
        default: focal
        type: string

jobs:
  debootstrap:
    runs-on: ubuntu-latest
    steps:
      - name: creating rootfs directory
        run: mkdir ./rootfs
      - name: running debootstrap
        run: debootstrap ${{ inputs.series }} ./rootfs http://archive.ubuntu.com
      - name: creating tarball
        run: tar czvf rootfs.tar.gz ./rootfs
      - name: Saving rootfs tarball
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.series }}-rootfs
          path: rootfs.tar.gz
