name: Build all series
on:
  workflow_dispatch:

jobs:
  jammy:
    uses: ./.github/workflows/build-image.yaml
    with:
      series: jammy

  oracular:
    uses: ./.github/workflows/build-image.yaml
    with:
      series: oracular

  noble:
    uses: ./.github/workflows/build-image.yaml
    with:
      series: noble

  plucky:
    uses: ./.github/workflows/build-image.yaml
    with:
      series: plucky
