name: Ubuntu image build
on:
  workflow_dispatch:
    inputs:
      series:
        description: Ubuntu series to build
        required: true
        default: focal
        type: string
      bootstrap_mirror:
        description: Mirror to use to bootstrap the system
        required: true
        default: http://archive.ubuntu.com/ubuntu
        type: string

jobs:
  debootstrap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: update APT cache
        run: sudo apt-get update
      - name: installing dependencies
        run: |
          sudo apt-get install -y \
                debootstrap
      - name: installing genesis
        run: sudo /opt/hostedtoolcache/Python/3.9.10/x64/bin/python -m pip install git+https://github.com/gjolly/genesis.git@cli
      - name: running debootstrap
        run: sudo genesis debootstrap --output ./rootfs --series ${{ github.event.inputs.series }}
      - name: creating tarball
        run: sudo tar czvf rootfs.tar.gz ./rootfs
      - name: Saving rootfs tarball
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.inputs.series }}-rootfs
          path: rootfs.tar.gz

  image-build:
    runs-on: ubuntu-latest
    needs: ['debootstrap']
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: update APT cache
        run: sudo apt-get update
      - name: installing dependencies
        run: |
          sudo apt-get install -y \
                qemu-utils \
                qemu-system-x86 \
                kpartx
      - name: installing genesis
        run: sudo /opt/hostedtoolcache/Python/3.9.10/x64/bin/python -m pip install git+https://github.com/gjolly/genesis.git@cli
      - uses: actions/download-artifact@master
        with:
          name: ${{ github.event.inputs.series }}-rootfs
          path: rootfs.tar.gz
      - name: untar rootfs
        run: tar xvf rootfs.tar.gz
      - name: creating disk-image
        run: sudo genesis create-disk --rootfs-dir ./rootfs
      - name: Updating the system
        run: |
          sudo genesis update-system \
            --disk-image disk.img \
            --series focal \
            --extra-package cloud-init \
            --extra-package openssh \
            --extra-package apt-transport-https \
            --extra-package ca-certificates \
            --extra-package linux-kvm
      - name: Install Grub
        run: |
          sudo genesis install-grub --disk-image disk.img
      - name: Converting to qcow2
        run: |
          sudo qemu-img convert -f raw -O qcow2 disk.img disk-image.img
      - name: Saving disk-image
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.inputs.series }}.img
          path: disk-image.img
