name: Ubuntu image build
on:
  workflow_dispatch:
    inputs:
      series:
        description: Ubuntu series to build
        required: true
        default: noble
        type: string
  workflow_call:
    inputs:
      series:
        description: Ubuntu series to build
        required: true
        default: noble
        type: string

# variables path are inconsistent when triggering with workflow_dispatch
# or workflow_call.
env:
  SERIES: ${{ github.event.inputs.series || inputs.series }}
  DEBIAN_FRONTEND: noninteractive

jobs:
  base-image:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: installing dependencies
        run: |
          sudo apt update && \
          sudo apt install -y mtools python3-venv python3-pip bubblewrap systemd-repart systemd-container
      - name: installing mkosi
        run: python3 -m venv mkosivenv && ls -la mkosivenv/bin/pip && ./mkosivenv/bin/pip install git+https://github.com/systemd/mkosi.git
      - name: creating disk-image
        run: sudo ./mkosivenv/bin/mkosi --release "${{ env.SERIES }}"
      - name: Saving disk-image
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.SERIES }}.img
          path: image.raw
