name: Ubuntu image build
on:
  workflow_dispatch:
    inputs:
      series:
        description: Ubuntu series to build
        required: true
        default: focal
        type: string
  workflow_call:
    inputs:
      series:
        description: Ubuntu series to build
        required: true
        default: focal
        type: string

# variables path are inconsistent when triggering with workflow_dispatch
# or workflow_call.
env:
  SERIES: ${{ github.event.inputs.series || inputs.series }}

jobs:
  base-image:
    runs-on: ubuntu-latest
    steps:
      - name: installing dependencies
        run: |
          sudo apt update && \
          sudo apt full-upgrade -y && sudo apt install -y mtools python3-venv
      - name: installing mkosi
        run: python3 -m venv mkosivenv && \
              ./mkosivenv/bin/pip install git+https://github.com/systemd/mkosi.git
      - name: creating disk-image
        run: sudo ./mkosivenv/bin/mkosi --release "${{ env.SERIES }}"
      - name: Saving disk-image
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.SERIES }}.img
          path: disk.img
