name: Build all series
on:
  workflow_dispatch:
  schedule:
    - cron: '13 6 * * *'

jobs:
  jammy:
    uses: ./.github/workflows/build-image.yaml
    with:
      series: jammy

  oracular:
    uses: ./.github/workflows/build-image.yaml
    with:
      series: oracular

  noble:
    uses: ./.github/workflows/build-image.yaml
    with:
      series: noble

  plucky:
    uses: ./.github/workflows/build-image.yaml
    with:
      series: plucky
