name: Ubuntu image build
on:
  workflow_dispatch:
    inputs:
      series:
        description: Ubuntu series to build
        required: true
        default: focal
        type: string
      mirror:
        description: Mirror to use after debootstrap
        required: true
        default: http://azure.archive.ubuntu.com/ubuntu
        type: string
  workflow_call:
    inputs:
      series:
        description: Ubuntu series to build
        required: true
        default: focal
        type: string
      mirror:
        description: Mirror to use after debootstrap
        required: true
        default: http://azure.archive.ubuntu.com/ubuntu
        type: string

# variables path are inconsistent when triggering with workflow_dispatch
# or workflow_call.
env:
  SERIES: ${{ github.event.inputs.series || inputs.series }}
  MIRROR: ${{ github.event.inputs.mirror || inputs.mirror }}

jobs:
  debootstrap:
    runs-on: ubuntu-latest
    steps:
      - name: update APT cache
        run: sudo apt-get update
      - name: installing dependencies
        run: |
          sudo apt-get update && \
          sudo apt-get install -y \
                debootstrap
      - name: installing genesis
        run: sudo python3 -m pip install git+https://github.com/gjolly/genesis.git@cli
      - name: running debootstrap
        run: sudo genesis debootstrap --output ./rootfs --series $SERIES
      - name: creating tarball
        run: sudo tar czvf rootfs.tar.gz ./rootfs
      - name: Saving rootfs tarball
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.SERIES }}-rootfs.tar.gz
          path: rootfs.tar.gz

  base-image:
    runs-on: ubuntu-latest
    needs: ['debootstrap']
    steps:
      - name: update APT cache
        run: sudo apt-get update
      - name: installing dependencies
        run: |
          sudo apt-get update && \
          sudo apt-get install -y \
                qemu-utils \
                kpartx
      - name: installing genesis
        run: sudo python3 -m pip install git+https://github.com/gjolly/genesis.git@cli
      - uses: actions/download-artifact@master
        with:
          name: ${{ env.SERIES }}-rootfs.tar.gz
      - name: extract rootfs
        run: sudo tar xf rootfs.tar.gz
      - name: creating disk-image
        run: sudo genesis create-disk --rootfs-dir ./rootfs
      - name: Updating the system
        run: |
          sudo genesis update-system \
            --disk-image disk.img \
            --mirror "$MIRROR" \
            --series "$SERIES" \
            --extra-package vim \
            --extra-package ca-certificate \
            --extra-package openssh-server \
            --extra-package cloud-init \
            --extra-package curl \
            --extra-package linux-generic
      - name: Install Grub
        run: |
          sudo genesis install-grub --disk-image disk.img
      - name: Converting to qcow2
        run: |
          sudo qemu-img convert -f raw -O qcow2 disk.img $SERIES.img
      - name: Saving disk-image
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.SERIES }}.img
          path: ${{ env.SERIES }}.img
