name: Build all series
on:
  workflow_dispatch:
  schedule:
    - cron: '13 6 * * *'

jobs:
  jammy:
    uses: ./.github/workflows/build-image.yaml
    with:
      series: jammy
    secrets: inherit

  oracular:
    uses: ./.github/workflows/build-image.yaml
    with:
      series: oracular
    secrets: inherit

  noble:
    uses: ./.github/workflows/build-image.yaml
    with:
      series: noble
    secrets: inherit

  plucky:
    uses: ./.github/workflows/build-image.yaml
    with:
      series: plucky
    secrets: inherit
