name: Build all series
on:
  workflow_dispatch:

jobs:
  focal:
    uses: ./.github/workflows/build-image.yaml
    with:
      series: focal

  jammy:
    uses: ./.github/workflows/build-image.yaml
    with:
      series: jammy

  noble:
    uses: ./.github/workflows/build-image.yaml
    with:
      series: noble
